server:
  port: 9001
auth:
  jwt:
    secret: "4=a^sjzA/-n49m^ZP(@ad>H"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    uri: "amqp://admin:admin@localhost:5672"


