app:
  server:
    port: {$PORT}

spring:
  datasource:
    url: jdbc:postgresql://ec2-44-194-4-127.compute-1.amazonaws.com:5432/df31bd0al0f1uh
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
