server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

devspot:
  kafka:
    broker:
      url: localhost:29092