server:
  port: ${SERVER_PORT:9001}
auth:
  jwt:
    secret: ${JWT_SECRET:4=a^sjzA/-n49m^ZP(@ad>H}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    uri: ${SPRING_RABBITMQ_URI:amqp://admin:admin@localhost:5672}
series:
  end: ${SERIES_END:2024-12-31:23:59}



