server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://ec2-52-48-159-67.eu-west-1.compute.amazonaws.com:5432/d3it7moaud42nh
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml


