@startuml
'https://plantuml.com/sequence-diagram

autonumber
== Password reset ==
actor User as User
    User -> FE: Clicks the link for password reset
    return Redirects the user to a form to collect the user's email

    User -> FE: Fills and sends the email
    FE -> AUTH_SERVICE: **POST** /password/reset
    activate AUTH_SERVICE
        AUTH_SERVICE -> AUTH_SERVICE: validates the email
        alt User with given email not found
                FE <-- AUTH_SERVICE: Return error
                User <-- FE: Shows failed message "User with given email not registered"
        end

        AUTH_SERVICE -> AUTH_SERVICE: Generates a unique hash and sends it to the email
        FE <-- AUTH_SERVICE: 200 OK - Email sent

        alt Something went wrong while sending email
            AUTH_SERVICE --> FE: 400 Bad Request - Email not sent
        end

deactivate AUTH_SERVICE
FE --> User: Displays result info

== User clicks the link in the email ==
User --> FE: Gets redirected to a page with loader
activate FE
    FE --> AUTH_SERVICE: **POST** /reset-link/validate
    activate AUTH_SERVICE
    AUTH_SERVICE -> AUTH_SERVICE: Perform validations
    alt validations failed
        AUTH_SERVICE --> FE: 409 Conflict - Link expired or not valid
        FE --> User: Redirect to login page (?) and show message
    end
    AUTH_SERVICE -> FE: 200 OK
    deactivate AUTH_SERVICE
    FE --> User: Display the password reset form
deactivate FE

== User fills a new password and submits form ==
User -> FE: User click the submit button
activate FE
FE -> FE: Performs validations (password same)
alt validations failed
    FE -> FE: Display error info
end
FE -> AUTH_SERVICE: PUT /password/update
activate AUTH_SERVICE
AUTH_SERVICE -> AUTH_SERVICE: Perform validations
    alt validations failed
        AUTH_SERVICE --> FE: 400 Bad Request
        FE --> User: Show message
    end
AUTH_SERVICE -> FE: 200 OK
deactivate AUTH_SERVICE
FE -> User: Redirect to login page
deactivate FE
@enduml